// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZVwooZgYVNZRcapz5lHPKqSevEe4AWIk',
    appId: '1:1079332845190:web:3a26fd14fa080838228307',
    messagingSenderId: '1079332845190',
    projectId: 'capstonedb-a8a1e',
    authDomain: 'capstonedb-a8a1e.firebaseapp.com',
    storageBucket: 'capstonedb-a8a1e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC29cy2ut7WIVuhWaolcC_giN2Dpa-5x7U',
    appId: '1:1079332845190:android:bfa517dc9e3b6e3c228307',
    messagingSenderId: '1079332845190',
    projectId: 'capstonedb-a8a1e',
    storageBucket: 'capstonedb-a8a1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChY4VLuZ8aIn0wEJOOncbCmo_R8rhoQXA',
    appId: '1:1079332845190:ios:d3a23af02a5e69be228307',
    messagingSenderId: '1079332845190',
    projectId: 'capstonedb-a8a1e',
    storageBucket: 'capstonedb-a8a1e.appspot.com',
    iosBundleId: 'com.example.petpals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChY4VLuZ8aIn0wEJOOncbCmo_R8rhoQXA',
    appId: '1:1079332845190:ios:d3a23af02a5e69be228307',
    messagingSenderId: '1079332845190',
    projectId: 'capstonedb-a8a1e',
    storageBucket: 'capstonedb-a8a1e.appspot.com',
    iosBundleId: 'com.example.petpals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZVwooZgYVNZRcapz5lHPKqSevEe4AWIk',
    appId: '1:1079332845190:web:34af01b385602692228307',
    messagingSenderId: '1079332845190',
    projectId: 'capstonedb-a8a1e',
    authDomain: 'capstonedb-a8a1e.firebaseapp.com',
    storageBucket: 'capstonedb-a8a1e.appspot.com',
  );

}